name: Messe Monitoring

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Install dependencies
       run: |
      	pip install requests beautifulsoup4 playwright
        playwright install chromium

        
      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scripts/auma_scraper.py
